BrainTravel/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from BrainTravel import settings

urlpatterns = patterns('',
    # Examples:
    url(r'^planner/list_venues/$', 'principal.views.FoursquareViews.foursquare_list_venues'),
    url(r'^planner/change_venue/$', 'principal.views.TripViews.change_venue'),
    url(r'^$', 'principal.views.MainViews.home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^signin/$', 'principal.views.UserViews.sign_in'),
    url(r'^logout/$', 'principal.views.UserViews.system_logout'),
    url(r'^search_trip/$', 'principal.views.TripViews.search_trip'),
    #Para indicar en las URLs un metodo que se encuentra dentro de un archivo .py
    # url(r'^<nombre_url>$', '<app>.<paquete>.<archivo>.<metodo>'),
    # url(r'^<nombre_url>$', 'principal.views.ViewsModel1.method1')
    url(r'^register_traveller/$', 'principal.views.UserViews.create_traveller'),
    url(r'^confirm_account/$', 'principal.views.UserViews.confirm_account'),
    url(r'^public_trip_details/(?P<trip_id>[0-9]+)$', 'principal.views.TripViews.public_trip_details'),
    url(r'^administrator/trip/list/$', 'principal.views.TripViews.list_trip_administrator'),
    url(r'^administrator/trip/update/(?P<trip_id>[0-9]+)$', 'principal.views.TripViews.update_state'),
    url(r'^coin/list/$', 'principal.views.Coinviews.list_coin_traveller'),
    url(r'^trip/mylist/$', 'principal.views.TripViews.list_all_by_traveller'),
    url(r'^trip/edit/(?P<trip_id>[0-9]+)$', 'principal.views.TripViews.trip_edit'),
    url(r'^trip/create/$', 'principal.views.TripViews.trip_create'),
    url(r'^judge/(?P<trip_id>[0-9]+)/(?P<like>[0-1])', 'principal.views.JudgeViews.judge'),
    url(r'^profile/(?P<traveller_id>[0-9]+)$', 'principal.views.TravellerViews.profile_details'),
    url(r'^profile/edit/$', 'principal.views.TravellerViews.profile_edit'),
    url(r'^profile/edit/password/$', 'principal.views.TravellerViews.profile_edit_password'),
    url(r'^trip/draft/$', 'principal.views.TripViews.list_all_by_traveller_draft'),
    # url(r'^auth_request/$', 'principal.views.FoursquareViews.foursquare_request'),
    url(r'^trip/list/(?P<profile_id>[0-9]+)$', 'principal.views.TripViews.list_trip_approved_by_profile'),
    url(r'^trip/planned_trips$', 'principal.views.TripViews.planned_trips'),
    url(r'^payment/$', 'principal.views.TravellerViews.all_payments'),
    url(r'^assessment/list/(?P<trip_id>[0-9]+)$', 'principal.views.AssessmentViews.assessment_list'),
    #paypal urls
    url(r'^buy_coins/$', 'principal.views.Coinviews.buy_coins'),
    url(r'^test_paypal/$', 'principal.views.PayPalViews.test_paypal_view'),
    url(r'^show_planning/(?P<trip_id>[0-9]+)/$', 'principal.views.FoursquareViews.show_planning'),
    url(r'^venue_details/(?P<id_venue>[0-9]+)$', 'principal.views.FoursquareViews.retrieve_venue'),
    url(r'^venue_details/rate/$', 'principal.views.TripViews.send_feedback'),
    url(r'^venue_details/value_tip/(?P<id_venue>[0-9]+)/(?P<id_tip>[0-9]+)$', 'principal.views.TripViews.value_tip'),
    url(r'^visited_venues/$', 'principal.views.VenueViews.visited_venues'),
    
    #Para llamadas en ajax
    url(r'^venue_details_json/(?P<id_venue>[0-9]+)/$', 'principal.views.VenueViews.venue_details_json'),
    url(r'^venues_to_change_json/(?P<id_trip>[0-9]+)/$', 'principal.views.VenueViews.venues_to_change_json'),
    
    url(r'^statistics/$', 'principal.views.TripViews.stats'),
    url(r'^cookies_policy/$', 'principal.views.UserViews.cookies_policies'),
    url(r'^about_us/$', 'principal.views.UserViews.about_us'),
    url(r'^privacy_terms/$', 'principal.views.UserViews.privacy_terms'),
    url(r'^stats/$', 'principal.views.TripViews.stats'),

    #planner URLs

    url(r'^something/paypal/', include('paypal.standard.ipn.urls')),
#     url(r'^paypal/return/$', 'principal.views.Coinviews.payment_return'),

    #i18n
    url(r'i18n/change_language', 'principal.views.TranslateViews.change_language'),
)

# if settings.DEBUG:
#     import debug_toolbar
# 
# urlpatterns += patterns('',
#                         url(r'^__debug__/', include(debug_toolbar.urls)),
# )

principal/models.py
# -*- coding: latin-1 -*-
import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# --------------------------- CUSTOMS VALIDATORS  ----------------------------------
def PastValidator(value):
    if value > datetime.datetime.now():
        raise ValidationError(u'' + str(value) + ' Is a future date!')


# -----------------------------------------------------------------------------------

# Create your models here.
class Administrator(User):
    class Meta:
        permissions = (
            ('administrator', 'Administrator'),
        )
        db_table = 'administrator'


class Category(models.Model):
    id_foursquare = models.CharField(max_length=30, unique=True)
    name = models.CharField(max_length=50)
    is_delete = models.BooleanField(default=False)

    class Meta:
        db_table = 'category'

    def __unicode__(self):
        return self.name


# Conceptually it's abstract, but Django not implement in BD abstract classes
class Scorable(models.Model):
    name = models.CharField(max_length=255)

    # ----------- Derivates -------------------------------#
    rating = models.FloatField(null=True, validators=[MinValueValidator(0), MaxValueValidator(10)])

    class Meta:
        db_table = 'scorable'


class Venue(Scorable):
    id_foursquare = models.CharField(max_length=30, unique=True)
    latitude = models.CharField(max_length=50)
    longitude = models.CharField(max_length=50)
    photo = models.CharField(max_length=256, null=True, blank=True)
    is_food = models.BooleanField(default=False)

    # ------------- Relationships --------------#
    categories = models.ManyToManyField(Category)

    class Meta:
        db_table = 'venue'

    def __unicode__(self):
        return self.name


class Feedback(models.Model):
    description = models.CharField(max_length=255, blank=False, null=False)
    leadTime = models.IntegerField(validators=[MinValueValidator(1)], null=True, blank=True)
    duration = models.IntegerField(validators=[MinValueValidator(1)], null=True, blank=True)

    # ---------- Derivate ---------------#
    usefulCount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])

    # ------------- Relationships --------------#
    traveller = models.ForeignKey('principal.Traveller')
    venues = models.ForeignKey(Venue) #Deberia ser Venue, en singular

    class Meta:
        db_table = 'feedback'


# class City(models.Model):
# name = models.CharField(max_length=50)
# country = models.CharField(max_length=50)
# description = models.TextField()
# 
#     class Meta:
#         db_table = 'city'
# 
#     def __unicode__(self):
#         return self.name


class Trip(Scorable):
    State = (
        ('ap', 'Approved'),
        ('re', 'Rejected'),
        ('pe', 'Pending'),
        ('df', 'Draft')
    )
    publishedDescription = models.TextField(null=True)
    startDate = models.DateField(null=True)
    endDate = models.DateField(null=True)
    planified = models.BooleanField(default=False)
    coins = models.IntegerField(validators=[MinValueValidator(0)])
    state = models.CharField(max_length=2, choices=State, default='pe')

    # ------------- Derivates -----------------------------#
    likes = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    dislikes = models.IntegerField(validators=[MinValueValidator(0)], default=0)

    # ------------- Relationships --------------#
    traveller = models.ForeignKey('principal.Traveller')
    # city = models.ForeignKey(City)
    city = models.CharField(max_length=50, null=False)
    country = models.CharField(max_length=50, null=False)
    possible_venues = models.ManyToManyField(Venue)
    

    class Meta:
        db_table = 'trip'

    def __unicode__(self):
        return 'Ini: ' + str(self.startDate) + 'End: ' + str(self.endDate)


class Traveller(User):
    Genre = (
        ('MA', 'MALE'),
        ('FE', 'FEMALE')
    )

    genre = models.CharField(max_length=2, choices=Genre, null=True)
    photo = models.ImageField(upload_to='static/user_folder/', null=True, default='static/user_folder/default.jpg')

    # ----------- Derivates -------------------#
    reputation = models.FloatField(null=True, blank=True,
                                   validators=[MinValueValidator(0), MaxValueValidator(10)])
    coins = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    recommendations = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    
    # ------------- Relationships --------------#
    likedFeedback = models.ManyToManyField(Feedback, through='Likes', related_name='traveller_likes')
    jugedTrips = models.ManyToManyField(Trip, through='Judges', related_name='judges')
    commentedTrips = models.ManyToManyField(Trip, through='Comment', related_name='commenters')
    assessedScorables = models.ManyToManyField(Scorable, through='Assessment')
    
    
    class Meta:
        db_table = 'traveller'
        permissions = (
            ('traveller', 'Traveller'),
        )
    
    
    def __unicode__(self):
        return self.first_name
    
    
    def save(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            this = Traveller.objects.get(id=self.id)
            if this.photo != self.photo and this.photo.name != 'static/user_folder/default.jpg':
                this.photo.delete(save=False)
        except:
            # when new photo then we do nothing, normal case
            pass
        super(Traveller, self).save(*args, **kwargs)


class Notification(models.Model):
    text = models.CharField(max_length=255)
    viewed = models.BooleanField(default=False)
    # ------------- Relationships --------------#
    user = models.ForeignKey(Traveller)

    class Meta:
        db_table = 'notification'


class Likes(models.Model):
    useful = models.BooleanField(default=False)
    comment = models.CharField(max_length=255, null=True)

    # -------------- Relationships -------------------
    traveller = models.ForeignKey(Traveller)
    feedback = models.ForeignKey(Feedback)

    class Meta:
        unique_together = ('traveller', 'feedback')
        db_table = 'likes'


class Day(models.Model):
    numberDay = models.IntegerField(validators=[MinValueValidator(1)])
    date = models.DateField(null=True)

    # ------------- Relationships --------------#
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    venues = models.ManyToManyField(Venue, through='VenueDay')

    class Meta:
        db_table = 'day'

    def clean(self):
        if self in self.trip.day_set:
            raise ValidationError('The trip already contains this day!')

    def __unicode__(self):
        return 'Day: ' + str(self.numberDay)


class VenueDay(models.Model):
    order = models.IntegerField(validators=[MinValueValidator(1)])

    # ------------- Relationships --------------#
    venue = models.ForeignKey(Venue)
    day = models.ForeignKey(Day)

    class Meta:
        unique_together = ('venue', 'day')
        db_table = 'venue_day'


class Comment(models.Model):
    description = models.CharField(max_length=255, null=True)
    date = models.DateTimeField(auto_now=True)
    # ------------- Relationships --------------#
    traveller = models.ForeignKey(Traveller)
    trip = models.ForeignKey(Trip)

    class Meta:
        db_table = 'comment'


class Judges(models.Model):
    like = models.BooleanField(default=False)

    # ------------- Relationships --------------#
    traveller = models.ForeignKey(Traveller)
    trip = models.ForeignKey(Trip, related_name='judgedTrip')

    class Meta:
        unique_together = ('trip', 'traveller')
        db_table = 'judges'


class Payment(models.Model):
    amount = models.FloatField(validators=[MinValueValidator(0)])
    date = models.DateTimeField(validators=[PastValidator])

    # ------------- Relationships --------------#
    traveller = models.ForeignKey(Traveller)

    class Meta:
        db_table = 'payment'


class CoinHistory(models.Model):
    amount = models.IntegerField()
    date = models.DateTimeField(validators=[PastValidator])
    concept = models.CharField(max_length=255)

    # -------------     Relationships --------------#
    traveller = models.ForeignKey(Traveller)
    payment = models.OneToOneField(Payment, null=True, blank=True)
    trip = models.OneToOneField(Trip, null=True, blank=True)

    class Meta:
        db_table = 'coin_history'

    def __unicode__(self):
        return str(self.amount)


class Schedule(models.Model):
    day = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(7)])
    openingTime = models.CharField(null=True, max_length=128)
    closingTime = models.CharField(null=True, max_length=128)

    # ------------- Relationships --------------#
    venue = models.ForeignKey(Venue)

    class Meta:
        db_table = 'schedule'


class Assessment(models.Model):
    score = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    comment = models.CharField(max_length=255)

    # ------------- Relationships --------------#
    traveller = models.ForeignKey(Traveller)
    scorable = models.ForeignKey(Scorable)

    class Meta:
        db_table = 'assessment'

principal/views/AssessmentViews.py
# -*- coding: iso-8859-1 -*-
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from principal.services import TripService, AssessmentService
from django.shortcuts import render_to_response
from django.template.context import RequestContext


def assessment_list(request, trip_id):
    try:
        assert request.user.has_perm('principal.traveller')
        trip = TripService.find_one(trip_id)
        assert trip.traveller.id == request.user.id
        assessments = AssessmentService.find_all_id_trip(trip_id)

        paginator = Paginator(assessments, 10)
        page = request.GET.get('page')
        try:
            assessments = paginator.page(page)
        except PageNotAnInteger:
            assessments = paginator.page(1)
        except EmptyPage:
            assessments = paginator.page(paginator.num_pages)

        return render_to_response('assessment_list.html', {'assessments': assessments}, context_instance=RequestContext(request))
    except Exception:
        return render_to_response('error.html', context_instance=RequestContext(request))

principal/views/EmailViews.py
# -*- coding: utf-8 -*-
from django.template.loader import render_to_string
from django.core.mail.message import EmailMessage
import hashlib
from django.utils import translation
from django.utils.translation import ugettext as _

def send_email_confirmation(traveller, rand_password):
    hash_confirm = hashlib.sha256(traveller.username).hexdigest()
    if translation.get_language() == "es":
        send_templated_email = render_to_string('email/register_confirmation_es.html',
                                                {'hash': hash_confirm, 'username': traveller.username,
                                                 'name': traveller.first_name,
                                                 'rand_password': rand_password})
        email = EmailMessage(_('Welcome to BrainTravel'), send_templated_email, to=[traveller.email])
        email.content_subtype = "html"
        email.send()
    else:
        send_templated_email = render_to_string('email/register_confirmation_en.html',
                                                {'hash': hash_confirm, 'username': traveller.username,
                                                 'name': traveller.first_name,
                                                 'rand_password': rand_password})
        email = EmailMessage('Bienvenido BrainTravel', send_templated_email, to=[traveller.email])
        email.content_subtype = "html"
        email.send()


def send_email_user_data(user, request):
    send_templated_email = render_to_string('email/email_user_data.html', {'request': request})
    email = EmailMessage('El usuario '+user.username+' acaba hacer login', send_templated_email,
                         to=['carlosborja93@gmail.com'])
    email.content_subtype = "html"
    email.send()

principal/views/MainViews.py
# -*- coding: iso-8859-1 -*-

from django.shortcuts import render_to_response
from django.template.context import RequestContext


def home(request):
    return render_to_response('index.html', {}, context_instance=RequestContext(request))

principal/views/PayPalViews.py
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response


from BrainTravel import settings
from principal.forms import FormPaypalOwn


def test_paypal_view(request):
    # What you want the button to do.
    paypal_dict = {
        "business": settings.PAYPAL_RECEIVER_EMAIL,
        "amount": "10000000.00",
        "item_name": "name of the item",
        "invoice": "unique-invoice-id10",
        "notify_url": "http://564027ec.ngrok.com" + reverse('paypal-ipn'),
        "return_url": "http://564027ec.ngrok.com",
        "cancel_return": "https://www.example.com/your-cancel-location/",
    }

    # Create the instance.
    form = FormPaypalOwn(initial=paypal_dict, button_type="buy")
    context = {"form": form}
    return render_to_response("payment.html", context)

principal/templates/about_us_en.html
{% extends 'base.html' %}
{% block title %}About us{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 text-justify">
            <h2>About us</h2>
            <p>
            <a href="http://54.69.54.93">BrainTravel </a>is owned by BrainTravel Co., Inc.
            </p>
            <p>
            Resident of Sevilla (41200)
            CIF: 123456789
            </p>
            <p>
            Registration Information: Registered in the Commercial Register of Seville, Date: 01/01/2015, Contract No.: 169011 BORME
            </p>
            <p>
            The website <a href="http://54.69.54.93">BrainTravel</a>is operated by BrainTravel Co., Inc. (the owner) as company.
            </p>
            <p>
            For any problem with it, contact the email <a href="mailto:clientes.braintravel@gmail.com"> clientes.braintravel@gmail.com </a>
            or phone +34 955555555
            </p>
           
        </div>
    </div>
</div>
{% endblock %}

principal/templates/assessment_list.html
{% extends 'base.html' %}
{% block title %} Assessment {% endblock %}
{% block content %}
    {% load i18n %}
<div class="container">
    <h1>{% trans "Assessment list" %}</h1>
    {% if not assessments %}
        <p>{% trans "Oops! BrainTravel could not find anything..." %}</p>
    {% else %}
        {% for assessment in assessments %}
            <div class="well col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="media">
                    <div class="row">
                        <div class="col-xs-offset-4 col-xs-4 col-sm-offset-0 col-sm-2 col-md-offset-0 col-md-2 col-lg-offset-0 col-lg-2">
                            <a href="/profile/{{ assessment.traveller.id }}">
                                <img class="img-rounded img-responsive img-circle" src="/{{assessment.traveller.photo}}" title="{{ assessment.traveller.first_name }}" width="150px"/>
                            </a>
                        </div>
                        <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
                            <p><span style="font-size: 40px"><i class="fa fa-star fa"  style="text-decoration: None"></i> {{ assessment.score }}</span></p>
                            <p style="font-size: 20px; text-align: justify">{{ assessment.comment }}</p>
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
        
    <nav class="col-xs-12">
        <ul class="pager">
            <li {% if not assessments.has_previous %} class="disabled"{% endif %}>
                <a {% if assessments.has_previous %} href="?page={{ assessments.previous_page_number }}"{% endif %}><span aria-hidden="true">&laquo;</span></a>
            </li>
    
            <li>
              <span>{% trans "Page" %} {{ assessments.number }} {% trans "of" %} {{ assessments.paginator.num_pages }}</span>
            </li>
    
            <li {% if not assessments.has_next %} class="disabled"{% endif %}>
              <a {% if assessments.has_next %} href="?page={{ assessments.next_page_number }}"{% endif %}><span aria-hidden="true" class="disabled">&raquo;</span></a></li>
        </ul>
    </nav>

    {% endif %}
</div>
{%endblock%}

principal/templates/error.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %} {% trans "Error" %} {% endblock %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <div class="text-center" style="margin-top:100px">
        <h1>{% trans "We are sorry. An error has occurred." %}</h1>
        <h4><a href="/"><i class="fa fa-arrow-left"></i> {% trans "Go to index" %}</a></h4>
        <img src="/static/img/access_denied.png" width="300" class="center-block img-circle img-thumbnail img-responsive">
    </div>
</div>
{% endblock %}

principal/templates/payment.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %} {% trans "My trips" %} {% endblock %}
{% block content %}

 <h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}


{% endblock %}

principal/templates/profile_edit.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %} {% trans "Edit profile" %} {% endblock %}
{% block content %}

<div class="container">
    <h1>{% trans "Edit Profile" %}</h1>
    {% if form.errors %}
        <div class="alert alert-danger alert-dismissible col-xs-12 col-sm-12 col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {% if  form.visible_fields.0.errors%}
                <strong>{% trans "First name" %}</strong>
                {{ form.visible_fields.0.errors }}
            {% endif %}
            {% if  form.visible_fields.1.errors%}
                <strong>{% trans "Last name" %}/strong>
                {{ form.visible_fields.1.errors }}
            {% endif %}
            {% if  form.visible_fields.2.errors%}
                <strong>{% trans "Genre" %}</strong>
                {{ form.visible_fields.2.errors }}
            {% endif %}
            {% if  form.visible_fields.3.errors or form.visible_fields.4.errors %}
                <strong>{% trans "Photo" %}</strong>
                {{ form.visible_fields.3.errors }}
                {{ form.visible_fields.4.errors }}
            {% endif %}
        </div>
    {% endif %}
    <div class="col-xs-12 col-sm-12 col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10">

        <div class="row">
            <form class="form-horizontal" role="form" action="/profile/edit/" method="post" data-toggle="validator"  enctype="multipart/form-data">
                {% csrf_token %}
                <!-- left column -->
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
                    <div class="form-group">
                        <div class="text-center ">
                            <img src="/{{ photo_profile }}" alt="" class="center-block img-circle img-thumbnail img-responsive" width="188">
                        </div>
                        <label for="id_photo" class="control-label"></label>
                        <div>
                            {{ form.visible_fields.4 }} <label for="id_photo_clear">{% trans "Default image" %}</label>
                            {{ form.visible_fields.3 }}
                        </div>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <!-- edit form column -->
                <div class="col-xs-12 col-sm-offset-1 col-sm-6 col-md-offset-1 col-md-6 col-lg-offset-1 col-lg-6">
                        <div class="form-group">
                            <label for="id_first_name" class="control-label">{% trans "First name" %}:</label>
                            {{ form.visible_fields.0 }}
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_last_name" class="control-label">{% trans "Last name" %}:</label>
                            {{ form.visible_fields.1 }}
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_genre" class="control-label">{% trans "Genre" %}:</label>
                            {{ form.visible_fields.2 }}
                            <div class="help-block with-errors"></div>
                        </div>
                        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                        <div class="form-group">
                            <input class="btn btn-primary" value={% trans "Save Changes" %} type="submit">
                            <span></span>
                            <a href="/profile/{{ form.id.value }}" class="btn btn-default">{% trans "Cancel" %}</a>
                        </div>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

principal/templates/trip_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %} {% trans "Trip list" %} {% endblock %}
{% block content %}
<div class="container">
    {% load i18n %}
    <h1>{{ title_list }}</h1>
    {% if not trips %}
        <p>{% trans "Oops! BrainTravel could not find anything..." %}</p>
    {% else %}
        {% for trip in trips %}
            <div class="well animated col-xs-12">
                <div class="media">
                    <div class="row">
                        <div class="text-center col-xs-12">
                            <h2>{{trip.name}}</h2>
                        </div>
                        <div class="text-right-center col-xs-12">
                            <p><i class="fa fa-globe fa-1x"></i> {{trip.city|safe}} ({{trip.country|safe}})</p>
                        </div>
                        <div class="text-justify col-xs-12">
                            <p>{{trip.publishedDescription|safe|truncatechars_html:350}}</p>
                        </div>
                        <div class="clearfix"></div>
                        <div class="text-left-center col-xs-12 col-sm-12 col-md-5 col-lg-5">
                            <p><i class="fa fa-calendar"></i> {{trip.startDate}} - {{trip.endDate}}</p>
                        </div>
                        <div class="text-right-center col-xs-12 col-sm-12 col-md-7 col-lg-offset-1 col-lg-6">
                            <ul class="list-inline list-unstyled">
                                <li> {% trans trip.get_state_display %}</li>
                                <li>|</li>
                                <li> {{trip.comment_set.all.count}} <i class="fa fa-comments"></i></li>
                                <li>|</li>
                                <li><i class="fa fa-thumbs-o-up"></i> {{trip.likes}}</li>
                                <li>|</li>
                                <li><i class="fa fa-thumbs-o-down"></i> {{trip.dislikes}}</li>
                                <li>|</li>
                                <li><i class="fa fa-star fa"></i> {% firstof trip.scorable_ptr.rating  ' -' %} / 10</li>
                                <li><a href="/public_trip_details/{{trip.scorable_ptr_id}}" style="text-decoration: None;"><i class="fa fa-info-circle"></i> {% trans "View more" %}</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        
        <nav class="col-xs-12">
              <ul class="pager">
                <li {% if not trips.has_previous %} class="disabled" {% endif %}>
                  <a {% if trips.has_previous %} href="?page={{ trips.previous_page_number }}" {% endif %}><span aria-hidden="true">&laquo;</span></a>
                </li>
                
                <li>
                 <span>{% trans "Page" %} {{ trips.number }} {% trans "of" %} {{ trips.paginator.num_pages }}</span>
                </li>
                
                <li {% if not trips.has_next %} class="disabled" {% endif %}>
                    <a {% if trips.has_next %} href="?page={{ trips.next_page_number }}" {% endif %}><span aria-hidden="true" class="disabled" >&raquo;</span></a>  
                </li>
              </ul>
            </nav>
    {% endif %}
</div>
{%endblock%}